// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Artist struct {
	ID        int              `json:"id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Song struct {
	ID          int              `json:"id"`
	ArtistID    int              `json:"artist_id"`
	Title       string           `json:"title"`
	ReleaseDate pgtype.Date      `json:"release_date"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Verse struct {
	ID          int              `json:"id"`
	SongID      int              `json:"song_id"`
	VerseNumber int              `json:"verse_number"`
	Text        string           `json:"text"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}
