// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetVersesBySongName(ctx context.Context, arg GetVersesBySongNameParams) ([]GetVersesBySongNameRow, error)
}

var _ Querier = (*Queries)(nil)
