// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: verses.sql

package sqlc

import (
	"context"
)

const getVersesBySongName = `-- name: GetVersesBySongName :many
SELECT
    v.verse_number,
    v.text
FROM
    verses v
        JOIN
    songs s ON v.song_id = s.id
WHERE
    s.title = $1
ORDER BY
    v.verse_number
LIMIT $2 OFFSET $3
`

type GetVersesBySongNameParams struct {
	Title  string `json:"title"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type GetVersesBySongNameRow struct {
	VerseNumber int    `json:"verse_number"`
	Text        string `json:"text"`
}

func (q *Queries) GetVersesBySongName(ctx context.Context, arg GetVersesBySongNameParams) ([]GetVersesBySongNameRow, error) {
	rows, err := q.db.Query(ctx, getVersesBySongName, arg.Title, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVersesBySongNameRow
	for rows.Next() {
		var i GetVersesBySongNameRow
		if err := rows.Scan(&i.VerseNumber, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
